sudo: required
services:
  - docker

before_install:
  - docker build -t nasserheydari/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true nasserheydari/react-test npm test -- --coverage

after_success:
  - docker build -t nasserheydari/multi-client ./client
  - docker build -t nasserheydari/multi-nginx ./nginx
  - docker build -t nasserheydari/multi-server ./server
  - docker build -t nasserheydari/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nasserheydari/multi-client
  - docker push nasserheydari/multi-nginx
  - docker push nasserheydari/multi-server
  - docker push nasserheydari/multi-worker
